- name: demo to get aws parameter name value using playbook
  hosts: all
  tasks:

  - name: getting the value for sample parameter using aws parameter store concept
    debug: msg="{{lookup('amazon.aws.aws_ssm', 'sample',region='us-east-1') }}"