- name: using playbook with ansible facts
  hosts: localhost
  tasks:
    - name: using debug module
      ansible.builtin.debug:
        msg: " {{ ansible_distribution_major_version }}"

- name: print all available facts
  hosts: localhost
  tasks:
    - name: using debug module
      ansible.builtin.debug:
        var: ansible_facts